# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: VVK-vapauskartat
email: adele@solita.fi
description: >
  Vapauskartat ovat reaaliaikaisesti päivittyviä karttoja, jotka
  kertovat lähistön todellisen varaustilanteen. Varaustieto kerätään
  reaaliaikaisesti antureilla tai muista tietolähteistä.
baseurl: ""
url: "http://koneidenkapinaadele.github.io/vvk/"
twitter_username: jekyllrb
github_username:  KoneidenKapinaAdele

# Build settings
markdown: kramdown
